### ISSUE TITLE
unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by drewtunney** [jormon/minimal-chrome-on-heroku#3]
I cloned the repository and pushed to heroku and received the following error:

Have you seen this before? Is this an known issue? 

```
Running thor runner:website on ⬢ ancient-bastion-58848... up, run.3929 (Free)
/app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': unknown error: Chrome failed to start: exited abnormally (Selenium::WebDriver::Error::UnknownError)
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /app/.apt/opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.4.0-1027-aws x86_64)
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/remote/bridge.rb:53:in `handshake'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/chrome/driver.rb:47:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/common/driver.rb:44:in `new'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/common/driver.rb:44:in `for'
	from /app/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver.rb:86:in `for'
	from /app/vendor/bundle/ruby/2.3.0/gems/watir-6.11.0/lib/watir/browser.rb:48:in `initialize'
	from /app/runner.thor:58:in `new'
	from /app/runner.thor:58:in `new_browser'
	from /app/runner.thor:13:in `website'
```

**Comment by jormon** [comment]
Hi sorry Drew, I haven't seen this, but I'll try and take a look this weekend.

**Comment by jamintz** [comment]
I'm getting the same issue on Heroku-16, it was working fine until a few days ago.

 $ chromedriver -v
ChromeDriver 70.0.3538.16 (16ed95b41bb05e565b11fb66ac33c660b721f778)

Also (maybe related) running google-chrome returns an error:
~ $ google-chrome
/app/.apt/opt/google/chrome/chrome: symbol lookup error: /app/.apt/usr/lib/x86_64-linux-gnu/libatk-1.0.so.0: undefined symbol: g_log_structured_standard

**Comment by jormon** [comment]
`chromedriver-helper` had a version bump in the aug/sept timeframe that did break the code.  I just pushed #4 -- maybe this will help you?  Apologies for the long delay...

**Comment by drewtunney** [comment]
I've moved on but I appreciate you taking a look @jormon! 😃

**Comment by jormon** [comment]
OK, no worries.  Closing out then.
